import { Project, Product, BlogPost } from './types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'Organic Maize Expansion',
    description: 'Scaling a 50-acre organic maize farm with modern irrigation and storage facilities.',
    fullDescription: 'This project aims to expand our current organic maize production by 50 acres. We will implement smart irrigation systems to ensure year-round cultivation and build a state-of-the-art storage facility to minimize post-harvest losses. The project is located in the fertile Green Valley region, known for its excellent soil quality.',
    location: 'Green Valley, Central Region',
    targetAmount: 5500000,
    raisedAmount: 3750000,
    investorsCount: 18,
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=800',
    category: 'Crops',
    returns: '15%',
    duration: '12 Months',
    highlights: ['Smart Irrigation', 'Post-harvest Storage', 'Organic Certified', 'Guaranteed Market'],
  },
  {
    id: '2',
    title: 'Smart Poultry System',
    description: 'Implementing automated feeding and climate control for a high-yield poultry farm.',
    fullDescription: 'Our smart poultry project focuses on integrating IoT technology into poultry farming. Automated feeding systems and climate control will optimize bird health and growth rates, leading to higher yields and better quality meat. This project is a pioneer in tech-driven livestock management.',
    location: 'North Plains, Highland District',
    targetAmount: 3500000,
    raisedAmount: 2800000,
    investorsCount: 24,
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&q=80&w=800',
    category: 'Livestock',
    returns: '18%',
    duration: '18 Months',
    highlights: ['IoT Monitoring', 'Automated Feeding', 'High Yield', 'Biosecurity Protocols'],
  },
  {
    id: '3',
    title: 'Sustainable Dairy Farm',
    description: 'Modernizing a dairy farm with sustainable waste management and premium breeds.',
    fullDescription: 'This dairy project involves the introduction of premium cattle breeds and the implementation of a biogas system for waste management. By converting waste into energy, we reduce our environmental footprint while producing high-quality dairy products for the local market.',
    location: 'River Basin, South Province',
    targetAmount: 8500000,
    raisedAmount: 4200000,
    investorsCount: 12,
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&q=80&w=800',
    category: 'Livestock',
    returns: '12%',
    duration: '24 Months',
    highlights: ['Premium Breeds', 'Biogas Energy', 'Sustainable Waste', 'Local Distribution'],
  },
  {
    id: '4',
    title: 'Greenhouse Tomato Project',
    description: 'Year-round tomato production using hydroponic systems in climate-controlled greenhouses.',
    fullDescription: 'Our greenhouse project utilizes hydroponic technology to grow tomatoes without soil. This method uses 90% less water and allows for year-round production regardless of external weather conditions. We aim to supply premium tomatoes to urban supermarkets.',
    location: 'Urban Fringe, Metro Area',
    targetAmount: 4500000,
    raisedAmount: 1500000,
    investorsCount: 9,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800',
    category: 'Vegetables',
    returns: '20%',
    duration: '9 Months',
    highlights: ['Hydroponics', 'Water Efficient', 'Year-round Harvest', 'Premium Pricing'],
  },
  // Adding 15 more projects
  ...Array.from({ length: 15 }).map((_, i) => ({
    id: (i + 5).toString(),
    title: `Agri Project ${i + 5}`,
    description: `A high-potential agricultural initiative focused on sustainable growth and innovation in category ${['Crops', 'Livestock', 'Vegetables', 'Fruits'][i % 4]}.`,
    fullDescription: `This project ${i + 5} is part of our strategic expansion into sustainable agriculture. We are leveraging modern technology and expert agronomy to ensure the highest possible yields and returns for our investors. The project includes comprehensive risk management and guaranteed market access for all produce.`,
    location: `${['Eastern', 'Western', 'Southern', 'Northern'][i % 4]} Region, Sector ${i + 1}`,
    targetAmount: 2000000 + (i * 500000),
    raisedAmount: 500000 + (i * 200000),
    investorsCount: 5 + i,
    image: `https://picsum.photos/seed/project${i + 5}/800/600`,
    category: ['Crops', 'Livestock', 'Vegetables', 'Fruits'][i % 4],
    returns: `${10 + (i % 10)}%`,
    duration: `${6 + (i % 18)} Months`,
    highlights: ['Modern Tech', 'Expert Management', 'Sustainability', 'Market Access'],
  }))
];

export const products: Product[] = [];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of Vertical Farming in Urban Areas',
    excerpt: 'How vertical farming is solving food security issues in densely populated cities across the globe.',
    content: 'Vertical farming is a revolutionary approach to agriculture that involves growing crops in vertically stacked layers. This method allows for significantly higher yields per square foot compared to traditional farming and can be implemented in urban environments, reducing the distance food travels from farm to table. In this article, we explore the technology behind vertical farming and its potential to transform our food systems...',
    date: 'Oct 12, 2023',
    author: 'Dr. Emily Green',
    image: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=800',
    category: 'Technology',
  },
  {
    id: '2',
    title: '5 Tips for Sustainable Soil Management',
    excerpt: 'Learn the best practices for maintaining soil health and increasing crop yields naturally.',
    content: 'Healthy soil is the foundation of productive agriculture. Sustainable soil management involves practices that maintain and enhance soil fertility, structure, and biological activity. From crop rotation to the use of organic fertilizers, these five tips will help you build resilient soil that supports high yields for generations to come...',
    date: 'Oct 08, 2023',
    author: 'Marcus Thorne',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&q=80&w=800',
    category: 'Farming Tips',
  },
  {
    id: '3',
    title: 'Why Agriculture is the Best Hedge Against Inflation',
    excerpt: 'An in-depth look at why agricultural investments remain stable during economic downturns.',
    content: 'In times of economic uncertainty and rising inflation, investors often look for "real assets" that hold their value. Agriculture is one such asset. Because the demand for food is inelastic—people need to eat regardless of the economy—agricultural land and production tend to perform well when other sectors struggle. We analyze the historical data and current trends that make agriculture a smart addition to any portfolio...',
    date: 'Sep 28, 2023',
    author: 'Sarah Chen',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    category: 'Investment',
  },
  {
    id: '4',
    title: 'The Rise of Smart Irrigation Systems',
    excerpt: 'How IoT and automated systems are reducing water waste and improving farm efficiency.',
    content: 'Water is one of the most precious resources in agriculture. Smart irrigation systems use IoT sensors and weather data to deliver the precise amount of water needed by crops, exactly when they need it. This not only saves water but also prevents over-irrigation and nutrient leaching, leading to healthier plants and lower costs for farmers...',
    date: 'Sep 15, 2023',
    author: 'David Wu',
    image: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&q=80&w=800',
    category: 'Technology',
  },
];
